openapi: 3.0.0
info:
  title: Account Transactions REST API
  version: "1.0"
servers:
  - url: http://localhost/
paths: { }
components:
  schemas:
    SupportedInstitution:
      type: string
      enum:
        - AMEX
        - CHASE
        - CITI
        - COASTAL
        - DISCOVER
        - SECU
    AccountTransactionFileEnvelope:
      type: object
      required:
        - accountId
        - file
        - supportedInstitution
      properties:
        accountId:
          type: integer
          minimum: 1
        file:
          type: string
          format: csv-file
        supportedInstitution:
          $ref: "#/components/schemas/SupportedInstitution"
