management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

# Everything above these dashes will be applied to all profiles
---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081

infrastructure:
  endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: dev

infrastructure:
  endpoint: http://infrastructure:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW