management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

authentication:
  provider-url: https://oauth2.googleapis.com/token
  authenticated-user-info-url: https://www.googleapis.com/oauth2/v2/userinfo
  client-id: 493888060498-vu55rlcj4p0sqbf1cpnr2k4am52r72qf.apps.googleusercontent.com

# Everything above these dashes will be applied to all profiles
---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080

infrastructure:
  endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: dev

infrastructure:
  endpoint: http://infrastructure:4566
  messaging:
    queue-url: ${infrastructure.endpoint}/000000000000/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW

---

spring:
  config:
    activate:
      on-profile: default

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:otterandcow.com.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: otterandcow.com

infrastructure:
  endpoint: https://sqs.us-east-1.amazonaws.com
  messaging:
    queue-url: ${infrastructure.endpoint}/654918520080/ACCOUNT_TRANSACTION_INGESTION_DATAFLOW