openapi: "3.0.2"
info:
  title: Common API
  version: "1.0"
servers:
  - url: http://localhost/
paths: { }
components:
  schemas:
    ReceiptResponse:
      type: object
      properties:
        receiptId:
          type: string
          example: "132b108e-ad98-472a-abb0-884f5032f5b8"
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
            example: "Something went wrong"

