name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  Pull-Request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "maven"

      - name: Build Application
        run: mvn clean install --no-transfer-progress

      #      - name: Build and analyze
      #        env:
      #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --no-transfer-progress \
      #          -Dsonar.organization=aaronsisler \
      #          -Dsonar.projectKey=aaronsisler_applications.paper-trail.financial-data-ingestion-service

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}